[language-server.iwe]
command = "iwes"

[[language]]
name = "markdown"
language-servers = ["iwe"]
auto-format = true

[[language]]
name = "c"
scope = "source.c"
injection-regex = "c"
file-types = ["c"]
indent = { tab-width = 2, unit = "\t" }
language-servers = [ "clangd" ]
